export const GAME_CONFIG = {
  WIDTH: 1920,
  HEIGHT: 1080,
  BG_COLOR: '#000000',
  PHYSICS: {
    GRAVITY_Y: 0,
    DEBUG: false
  },
  CAMERA: {
    LERP: 0.1,
    DEADZONE_WIDTH: 200,
    DEADZONE_HEIGHT: 200
  },
  VFX: {
    QUALITY_LEVEL: 'HIGH', // 'LOW', 'MEDIUM', 'HIGH'
    MAX_PETALS: { LOW: 15, MEDIUM: 25, HIGH: 35 },
    MAX_SPIRITS: { LOW: 6, MEDIUM: 12, HIGH: 18 },
    WIND: {
      PETAL_WIND_SPEED: 0.5,
      PETAL_FALL_SPEED: 0.3,
      PETAL_SWAY_AMOUNT: 1.5,
      PETAL_SWAY_FREQUENCY: 0.002,
      PETAL_SPAWN_RATE: 2000 // ms
    }
  },
  WORLD: {
    WIDTH: 3840,
    HEIGHT: 2160
  },
  PLAYER: {
    START_X: 1920,
    START_Y: 1080,
    MOVE_SPEED: 300
  },

  DEBUG_MODE: true
};
